name: Main

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleCi

      - name: Sign APK
        env:
          CI_SIGNING_KS: ${{ secrets.CI_SIGNING_KS }}
          CI_SIGNING_KS_PASSWORD: ${{ secrets.CI_SIGNING_KS_PASSWORD }}
        working-directory: ./app/build/outputs/apk/ci/
        run: |
          echo $CI_SIGNING_KS | base64 --decode > keystore.jks
          $ANDROID_HOME/build-tools/33.0.0/apksigner sign --in app-ci-unsigned.apk --out app-ci.apk --ks keystore.jks --ks-pass 'env:CI_SIGNING_KS_PASSWORD'

      - name: Upload APK
        uses: actions/upload-artifact@v3.1.1
        with:
          name: avnc-ci
          path: app/build/outputs/apk/ci/app-ci.apk